# configuration settings for chest x ray classification

general_configs:
  dataset path: E:/xray classification/Data/chest_xray
  dataset splitted: E:/xray classification/COVID/splitted/data/COVID-19_Radiography_Dataset

# Data augmentation options
Augmentation:
  resize: [224, 224]
  random_crop: 224
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]
  rotation: 
    angle: 45
  random_affine:
    rotation: 20
    translation: [0.2, 0.2]
    scaling: [0.1, 0.1]
    shear: 0.1
  zoomed_out: 0.3
  horizontal_flip: 0.5
  vertical_flip: 0.01

# data loading parameters
DataLoader:
  batch_size: 512
  num_workers: 4
  pin_memory: True
  data_shuffle: True
  num_classes: 4

Training:
  epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.00001
  model_name: 'resnet18'
